In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
sys.path.append('..')
from experanto.interpolators import SequenceInterpolator

import numpy as np


In [3]:
si = SequenceInterpolator('/Users/fabee/Data/sinzlab-data/dataset0/eye_tracker')

(100001,)


In [5]:
np.diff(si.timestamps)

array([0.05023909, 0.04981446, 0.04978514, ..., 0.05015039, 0.04984689,
       0.05011773])

In [6]:
times

array([1.6794195e+09, 1.6794195e+09, 1.6794195e+09, 1.6794195e+09,
       1.6794195e+09, 1.6794195e+09, 1.6794195e+09, 1.6794195e+09,
       1.6794195e+09, 1.6794195e+09])

In [23]:
times = si.timestamps[:10] + np.diff(si.timestamps)[:10] * 0.1
signal, valid = si.interpolate(times)

# assert np.all(np.abs(si._data[:10] - signal) < 1e-6)

In [19]:
# times = si.timestamps[:10] + np.diff(si.timestamps)[:10] * 0.9
# signal, valid = si.interpolate(times)

# assert np.all(np.abs(si._data[:10] - signal) < 1e-6)


AssertionError: 

In [25]:
signal 

array([[       nan, 0.07219061, 0.42020655],
       [0.29248611, 0.56352903, 0.12879458],
       [0.51282013, 0.58182862, 0.81029075],
       [0.31105545, 0.32086159,        nan],
       [0.9534322 , 0.83816156, 0.31449089],
       [0.32158147, 0.37847934, 0.64375469],
       [0.53659753, 0.42919402, 0.48491717],
       [0.71569698, 0.49469154, 0.84768188],
       [0.7108907 , 0.26814313, 0.39458303],
       [0.31520302, 0.79906747, 0.74750986]])

In [26]:
si._data[:10]

array([[0.60193101, 0.25632986, 0.60828988],
       [       nan, 0.07219061, 0.42020655],
       [0.29248611, 0.56352903, 0.12879458],
       [0.51282013, 0.58182862, 0.81029075],
       [0.31105545, 0.32086159,        nan],
       [0.9534322 , 0.83816156, 0.31449089],
       [0.32158147, 0.37847934, 0.64375469],
       [0.53659753, 0.42919402, 0.48491717],
       [0.71569698, 0.49469154, 0.84768188],
       [0.7108907 , 0.26814313, 0.39458303]])